import { cookies } from "next/headers";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
// 组件
import WebFooter from "@/components/WebFooter";

import "./globals.css";

import type { Metadata } from "next";
import { RequestCookie } from "next/dist/compiled/@edge-runtime/cookies";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const cookieStore = cookies();
	// 没有的话 则为auto 自适应
	const theme: RequestCookie | undefined = cookieStore.get("theme");
	console.log(theme, "===获取到theme===");
	const themeValue: string = theme?.value || "auto";
	return (
		<html lang='en'>
			<body className={themeValue}>
				{children}
				<WebFooter />
			</body>
		</html>
	);
}
